server:
  port: 8071
spring:
  application:
    name: payment-response-service
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pymtresp
    username: postgres
    password: Ecssupport09
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
logging:
  level:
    root: INFO